model:
  n_chans: 1
  n_classes: 

task : 1 # or 2 then we also need to change the things accordingly

training_params:
  batch_size: 16
  learning_rate: 0.001
  epochs: 100
  device: "cuda" if torch.cuda.is_available() else "cpu"