architecture : 'conformer'
model:
  emb_size : 40 # according to it we need to modify input channels of the pooling layer
  n_classes : 2
  depth : 8

contrastive : 'simclr'

vqvae:
  num_embeddings : 427 # num unique persons
  embedding_dim : 64
  commitment_cost : 10
  person_count : 427


training_params:
  batch_size: 16
  learning_rate: 0.001
  epochs: 100
  device: "cuda"